locals {
  policy = {
    business = {
      Version = "2012-10-17",
      Statement = [
        {
          Sid = "Stmt1664392197262",
          Action = [
            "ses:CloneReceiptRuleSet",
            "ses:CreateReceiptFilter",
            "ses:CreateReceiptRule",
            "ses:CreateReceiptRuleSet",
            "ses:DeleteIdentity",
            "ses:DeleteIdentityPolicy",
            "ses:DeleteReceiptFilter",
            "ses:DeleteReceiptRule",
            "ses:DeleteReceiptRuleSet",
            "ses:DeleteVerifiedEmailAddress",
            "ses:DescribeActiveReceiptRuleSet",
            "ses:DescribeConfigurationSet",
            "ses:DescribeReceiptRule",
            "ses:DescribeReceiptRuleSet",
            "ses:GetAccountSendingEnabled",
            "ses:GetIdentityDkimAttributes",
            "ses:GetIdentityMailFromDomainAttributes",
            "ses:GetIdentityNotificationAttributes",
            "ses:GetIdentityPolicies",
            "ses:GetIdentityVerificationAttributes",
            "ses:GetSendQuota",
            "ses:GetSendStatistics",
            "ses:ListIdentities",
            "ses:ListIdentityPolicies",
            "ses:ListReceiptFilters",
            "ses:ListReceiptRuleSets",
            "ses:ListVerifiedEmailAddresses",
            "ses:PutConfigurationSetDeliveryOptions",
            "ses:PutIdentityPolicy",
            "ses:ReorderReceiptRuleSet",
            "ses:SendBounce",
            "ses:SetActiveReceiptRuleSet",
            "ses:SetIdentityDkimEnabled",
            "ses:SetIdentityMailFromDomain",
            "ses:SetIdentityNotificationTopic",
            "ses:SetReceiptRulePosition",
            "ses:UpdateAccountSendingEnabled",
            "ses:UpdateConfigurationSetSendingEnabled",
            "ses:UpdateReceiptRule",
            "ses:VerifyDomainDkim",
            "ses:VerifyDomainIdentity",
            "ses:VerifyEmailAddress",
            "ses:VerifyEmailIdentity"
          ],
          Effect   = "Allow",
          Resource = "*"
        },
        {
          Sid = "Stmt1664392367315",
          Action = [
            "ses:CreateEmailIdentity",
            "ses:CreateEmailIdentityPolicy",
            "ses:DeleteEmailIdentity",
            "ses:DeleteEmailIdentityPolicy",
            "ses:GetAccount",
            "ses:GetBlacklistReports",
            "ses:GetConfigurationSet",
            "ses:GetConfigurationSetEventDestinations",
            "ses:GetDedicatedIp",
            "ses:GetDedicatedIps",
            "ses:GetEmailIdentity",
            "ses:GetEmailIdentityPolicies",
            "ses:ListEmailIdentities",
            "ses:PutAccountDetails",
            "ses:PutAccountSendingAttributes",
            "ses:PutConfigurationSetDeliveryOptions",
            "ses:PutConfigurationSetReputationOptions",
            "ses:PutConfigurationSetSendingOptions",
            "ses:PutDedicatedIpInPool",
            "ses:PutEmailIdentityMailFromAttributes",
            "ses:TagResource",
            "ses:UntagResource",
            "ses:UpdateEmailIdentityPolicy"
          ],
          Effect   = "Allow",
          Resource = "*"
        },
        {
          Sid      = "Stmt1664392409832",
          Action   = "support:*",
          Effect   = "Allow",
          Resource = "*"
        },
      ]
    }

    compute_ec2 = {
      Version = "2012-10-17",
      Statement = [
        {
          Sid = "Stmt1664390055903",
          Action = [
            "ec2:AllocateAddress",
            "ec2:AllocateHosts",
            "ec2:AssignPrivateIpAddresses",
            "ec2:AssociateAddress",
            "ec2:AssociateIamInstanceProfile",
            "ec2:AssociateRouteTable",
            "ec2:AssociateSubnetCidrBlock",
            "ec2:AssociateVpcCidrBlock",
            "ec2:AttachInternetGateway",
            "ec2:AttachNetworkInterface",
            "ec2:AttachVolume",
            "ec2:AuthorizeSecurityGroupEgress",
            "ec2:AuthorizeSecurityGroupIngress",
            "ec2:CopyImage",
            "ec2:CopySnapshot",
            "ec2:CreateDefaultSubnet",
            "ec2:CreateDefaultVpc",
            "ec2:CreateEgressOnlyInternetGateway",
            "ec2:CreateInternetGateway",
            "ec2:CreateKeyPair",
            "ec2:CreateLaunchTemplate",
            "ec2:CreateLaunchTemplateVersion",
            "ec2:CreateManagedPrefixList",
            "ec2:CreateNatGateway",
            "ec2:CreateNetworkAcl",
            "ec2:CreateNetworkAclEntry",
            "ec2:CreateNetworkInsightsAccessScope",
            "ec2:CreateNetworkInsightsPath",
            "ec2:CreateNetworkInterface",
            "ec2:CreateNetworkInterfacePermission",
            "ec2:CreatePlacementGroup",
            "ec2:CreatePublicIpv4Pool",
            "ec2:CreateRoute",
            "ec2:CreateRouteTable",
            "ec2:CreateSecurityGroup",
            "ec2:CreateSubnet",
            "ec2:CreateSubnetCidrReservation",
            "ec2:CreateTags",
            "ec2:CreateVolume",
            "ec2:CreateVpc",
            "ec2:DeleteEgressOnlyInternetGateway",
            "ec2:DeleteInternetGateway",
            "ec2:DeleteKeyPair",
            "ec2:DeleteLaunchTemplate",
            "ec2:DeleteLaunchTemplateVersions",
            "ec2:DeleteManagedPrefixList",
            "ec2:DeleteNatGateway",
            "ec2:DeleteNetworkAcl",
            "ec2:DeleteNetworkAclEntry",
            "ec2:DeleteNetworkInterface",
            "ec2:DeleteNetworkInterfacePermission",
            "ec2:DeletePlacementGroup",
            "ec2:DeletePublicIpv4Pool",
            "ec2:DeleteRoute",
            "ec2:DeleteRouteTable",
            "ec2:DeleteSecurityGroup",
            "ec2:DeleteSubnet",
            "ec2:DeleteSubnetCidrReservation",
            "ec2:DeleteTags",
            "ec2:DeleteVolume",
            "ec2:DeleteVpc",
            "ec2:DeprovisionPublicIpv4PoolCidr",
            "ec2:Describe*",
            "ec2:DetachInternetGateway",
            "ec2:DetachNetworkInterface",
            "ec2:DetachVolume",
            "ec2:DisableEbsEncryptionByDefault",
            "ec2:DisassociateAddress",
            "ec2:DisassociateEnclaveCertificateIamRole",
            "ec2:DisassociateIamInstanceProfile",
            "ec2:DisassociateRouteTable",
            "ec2:DisassociateSubnetCidrBlock",
            "ec2:DisassociateVpcCidrBlock",
            "ec2:EnableEbsEncryptionByDefault",
            "ec2:EnableVolumeIO",
            "ec2:GetAssociatedEnclaveCertificateIamRoles",
            "ec2:GetConsoleOutput",
            "ec2:GetEbsEncryptionByDefault",
            "ec2:GetInstanceTypesFromInstanceRequirements",
            "ec2:GetLaunchTemplateData",
            "ec2:GetManagedPrefixListAssociations",
            "ec2:GetManagedPrefixListEntries",
            "ec2:GetResourcePolicy",
            "ec2:GetSubnetCidrReservations",
            "ec2:ModifyAddressAttribute",
            "ec2:ModifyAvailabilityZoneGroup",
            "ec2:ModifyHosts",
            "ec2:ModifyInstanceCapacityReservationAttributes",
            "ec2:ModifyInstancePlacement",
            "ec2:ModifyLaunchTemplate",
            "ec2:ModifyNetworkInterfaceAttribute",
            "ec2:ModifySecurityGroupRules",
            "ec2:ModifySubnetAttribute",
            "ec2:ModifyVolume",
            "ec2:ModifyVolumeAttribute",
            "ec2:ModifyVpcAttribute",
            "ec2:MonitorInstances",
            "ec2:MoveAddressToVpc",
            "ec2:RegisterInstanceEventNotificationAttributes",
            "ec2:ReleaseAddress",
            "ec2:ReleaseHosts",
            "ec2:ReplaceNetworkAclAssociation",
            "ec2:ReplaceNetworkAclEntry",
            "ec2:ReplaceRoute",
            "ec2:ReplaceRouteTableAssociation",
            "ec2:RevokeClientVpnIngress",
            "ec2:RevokeSecurityGroupEgress",
            "ec2:RevokeSecurityGroupIngress",
            "ec2:RunInstances",
            "ec2:StartInstances",
            "ec2:StartNetworkInsightsAccessScopeAnalysis",
            "ec2:StartNetworkInsightsAnalysis",
            "ec2:StopInstances",
            "ec2:TerminateInstances",
            "ec2:UnassignPrivateIpAddresses",
            "ec2:UnmonitorInstances",
            "ec2:UpdateSecurityGroupRuleDescriptionsEgress",
            "ec2:UpdateSecurityGroupRuleDescriptionsIngress"
          ],
          Effect   = "Allow",
          Resource = "*"
        },
      ]
    }

    compute_autoscaling = {
      Version = "2012-10-17",
      Statement = [
        {
          Sid = "Stmt1664390222286",
          Action = [
            "autoscaling:AttachInstances",
            "autoscaling:AttachLoadBalancerTargetGroups",
            "autoscaling:AttachLoadBalancers",
            "autoscaling:CancelInstanceRefresh",
            "autoscaling:CompleteLifecycleAction",
            "autoscaling:CreateAutoScalingGroup",
            "autoscaling:CreateLaunchConfiguration",
            "autoscaling:CreateOrUpdateTags",
            "autoscaling:DeleteAutoScalingGroup",
            "autoscaling:DeleteLaunchConfiguration",
            "autoscaling:DeleteLifecycleHook",
            "autoscaling:DeleteNotificationConfiguration",
            "autoscaling:DeletePolicy",
            "autoscaling:DeleteTags",
            "autoscaling:Describe*",
            "autoscaling:DetachInstances",
            "autoscaling:DetachLoadBalancerTargetGroups",
            "autoscaling:DetachLoadBalancers",
            "autoscaling:DisableMetricsCollection",
            "autoscaling:EnableMetricsCollection",
            "autoscaling:EnterStandby",
            "autoscaling:ExecutePolicy",
            "autoscaling:ExitStandby",
            "autoscaling:PutLifecycleHook",
            "autoscaling:PutNotificationConfiguration",
            "autoscaling:PutScalingPolicy",
            "autoscaling:ResumeProcesses",
            "autoscaling:SetDesiredCapacity",
            "autoscaling:SetInstanceHealth",
            "autoscaling:SetInstanceProtection",
            "autoscaling:StartInstanceRefresh",
            "autoscaling:SuspendProcesses",
            "autoscaling:TerminateInstanceInAutoScalingGroup",
            "autoscaling:UpdateAutoScalingGroup"
          ],
          Effect   = "Allow",
          Resource = "*"
        },
      ]
    }

    compute_elasticloadbalancing = {
      Version = "2012-10-17",
      Statement = [
        {
          Sid = "Stmt1664390969881",
          Action = [
            "elasticloadbalancing:AddListenerCertificates",
            "elasticloadbalancing:AddTags",
            "elasticloadbalancing:CreateListener",
            "elasticloadbalancing:CreateLoadBalancer",
            "elasticloadbalancing:CreateRule",
            "elasticloadbalancing:CreateTargetGroup",
            "elasticloadbalancing:DeleteListener",
            "elasticloadbalancing:DeleteLoadBalancer",
            "elasticloadbalancing:DeleteRule",
            "elasticloadbalancing:DeleteTargetGroup",
            "elasticloadbalancing:DeregisterTargets",
            "elasticloadbalancing:Describe*",
            "elasticloadbalancing:ModifyListener",
            "elasticloadbalancing:ModifyLoadBalancerAttributes",
            "elasticloadbalancing:ModifyRule",
            "elasticloadbalancing:ModifyTargetGroup",
            "elasticloadbalancing:ModifyTargetGroupAttributes",
            "elasticloadbalancing:RegisterTargets",
            "elasticloadbalancing:RemoveListenerCertificates",
            "elasticloadbalancing:RemoveTags",
            "elasticloadbalancing:SetIpAddressType",
            "elasticloadbalancing:SetRulePriorities",
            "elasticloadbalancing:SetSecurityGroups",
            "elasticloadbalancing:SetSubnets",
            "elasticloadbalancing:SetWebAcl"
          ],
          Effect   = "Allow",
          Resource = "*"
        },
      ]
    }

    container = {
      Version = "2012-10-17",
      Statement = [
        {
          Sid = "Stmt1664390438238",
          Action = [
            "ecr:BatchCheckLayerAvailability",
            "ecr:BatchDeleteImage",
            "ecr:BatchGetImage",
            "ecr:BatchGetRepositoryScanningConfiguration",
            "ecr:CreatePullThroughCacheRule",
            "ecr:CreateRepository",
            "ecr:DeleteLifecyclePolicy",
            "ecr:DeletePullThroughCacheRule",
            "ecr:DeleteRegistryPolicy",
            "ecr:DeleteRepository",
            "ecr:DeleteRepositoryPolicy",
            "ecr:DescribeImageReplicationStatus",
            "ecr:DescribeImageScanFindings",
            "ecr:DescribeImages",
            "ecr:DescribePullThroughCacheRules",
            "ecr:DescribeRegistry",
            "ecr:DescribeRepositories",
            "ecr:GetAuthorizationToken",
            "ecr:GetLifecyclePolicy",
            "ecr:GetLifecyclePolicyPreview",
            "ecr:GetRegistryPolicy",
            "ecr:GetRegistryScanningConfiguration",
            "ecr:GetRepositoryPolicy",
            "ecr:ListImages",
            "ecr:ListTagsForResource",
            "ecr:PutImageScanningConfiguration",
            "ecr:PutImageTagMutability",
            "ecr:PutLifecyclePolicy",
            "ecr:PutRegistryPolicy",
            "ecr:SetRepositoryPolicy",
            "ecr:StartImageScan",
            "ecr:StartLifecyclePolicyPreview",
            "ecr:TagResource",
            "ecr:UntagResource"
          ],
          Effect   = "Allow",
          Resource = "*"
        },
        {
          Sid = "Stmt1664390609163",
          Action = [
            "ecs:CreateCapacityProvider",
            "ecs:CreateCluster",
            "ecs:DeleteAttributes",
            "ecs:DeleteCapacityProvider",
            "ecs:DeleteCluster",
            "ecs:DeleteService",
            "ecs:DeleteTaskSet",
            "ecs:DeregisterContainerInstance",
            "ecs:DeregisterTaskDefinition",
            "ecs:DescribeCapacityProviders",
            "ecs:DescribeClusters",
            "ecs:DescribeContainerInstances",
            "ecs:DescribeServices",
            "ecs:DescribeTaskDefinition",
            "ecs:DescribeTaskSets",
            "ecs:DescribeTasks",
            "ecs:ListAttributes",
            "ecs:ListClusters",
            "ecs:ListContainerInstances",
            "ecs:ListServices",
            "ecs:ListTagsForResource",
            "ecs:ListTaskDefinitionFamilies",
            "ecs:ListTaskDefinitions",
            "ecs:ListTasks",
            "ecs:Poll",
            "ecs:PutAttributes",
            "ecs:PutClusterCapacityProviders",
            "ecs:RegisterContainerInstance",
            "ecs:StopTask",
            "ecs:SubmitAttachmentStateChanges",
            "ecs:SubmitContainerStateChange",
            "ecs:TagResource",
            "ecs:UntagResource",
            "ecs:UpdateCluster",
            "ecs:UpdateClusterSettings",
            "ecs:UpdateContainerAgent",
            "ecs:UpdateContainerInstancesState"
          ],
          Effect   = "Allow",
          Resource = "*"
        },
      ]
    }

    database = {
      Version = "2012-10-17",
      Statement = [
        {
          Sid = "Stmt1664388294058",
          Action = [
            "dynamodb:GetItem",
            "dynamodb:PutItem",
            "dynamodb:DeleteItem"
          ],
          Effect   = "Allow",
          Resource = "*"
        },
      ]
    }

    monitoring = {
      Version = "2012-10-17",
      Statement = [
        {
          Sid = "Stmt1664387566231",
          Action = [
            "cloudwatch:DeleteAlarms",
            "cloudwatch:DeleteDashboards",
            "cloudwatch:DeleteMetricStream",
            "cloudwatch:DescribeAlarms",
            "cloudwatch:DescribeAlarmsForMetric",
            "cloudwatch:DescribeAnomalyDetectors",
            "cloudwatch:DisableAlarmActions",
            "cloudwatch:EnableAlarmActions",
            "cloudwatch:GetDashboard",
            "cloudwatch:GetMetricData",
            "cloudwatch:GetMetricStatistics",
            "cloudwatch:GetMetricStream",
            "cloudwatch:GetMetricWidgetImage",
            "cloudwatch:ListDashboards",
            "cloudwatch:ListMetricStreams",
            "cloudwatch:ListMetrics",
            "cloudwatch:ListTagsForResource",
            "cloudwatch:PutAnomalyDetector",
            "cloudwatch:PutCompositeAlarm",
            "cloudwatch:PutDashboard",
            "cloudwatch:PutMetricAlarm",
            "cloudwatch:PutMetricData",
            "cloudwatch:PutMetricStream",
            "cloudwatch:SetAlarmState",
            "cloudwatch:StartMetricStreams",
            "cloudwatch:StopMetricStreams",
            "cloudwatch:TagResource",
            "cloudwatch:UntagResource"
          ],
          Effect   = "Allow",
          Resource = "*"
        },
        {
          Sid = "Stmt1664387828387",
          Action = [
            "logs:CreateLogDelivery",
            "logs:CreateLogGroup",
            "logs:CreateLogStream",
            "logs:DeleteLogDelivery",
            "logs:DeleteLogGroup",
            "logs:DeleteLogStream",
            "logs:DescribeDestinations",
            "logs:DescribeLogGroups",
            "logs:DescribeLogStreams",
            "logs:DescribeMetricFilters",
            "logs:DescribeQueries",
            "logs:DescribeQueryDefinitions",
            "logs:DescribeResourcePolicies",
            "logs:DescribeSubscriptionFilters",
            "logs:FilterLogEvents",
            "logs:GetLogDelivery",
            "logs:GetLogEvents",
            "logs:GetLogGroupFields",
            "logs:GetLogRecord",
            "logs:GetQueryResults",
            "logs:ListLogDeliveries",
            "logs:ListTagsLogGroup",
            "logs:PutMetricFilter",
            "logs:PutQueryDefinition",
            "logs:PutResourcePolicy",
            "logs:PutRetentionPolicy",
            "logs:PutSubscriptionFilter",
            "logs:StartQuery",
            "logs:StopQuery",
            "logs:TagLogGroup",
            "logs:UntagLogGroup",
            "logs:UpdateLogDelivery"
          ],
          Effect   = "Allow",
          Resource = "*"
        },
      ]
    }

    networking = {
      Version = "2012-10-17",
      Statement = [
        {
          Sid = "Stmt1664387330947",
          Action = [
            "cloudfront:AssociateAlias",
            "cloudfront:CreateCachePolicy",
            "cloudfront:CreateDistribution",
            "cloudfront:CreateFieldLevelEncryptionConfig",
            "cloudfront:CreateFieldLevelEncryptionProfile",
            "cloudfront:CreateInvalidation",
            "cloudfront:CreateKeyGroup",
            "cloudfront:CreateMonitoringSubscription",
            "cloudfront:CreateOriginRequestPolicy",
            "cloudfront:CreatePublicKey",
            "cloudfront:CreateResponseHeadersPolicy",
            "cloudfront:DeleteCachePolicy",
            "cloudfront:DeleteDistribution",
            "cloudfront:DeleteFieldLevelEncryptionConfig",
            "cloudfront:DeleteFieldLevelEncryptionProfile",
            "cloudfront:DeleteKeyGroup",
            "cloudfront:DeleteMonitoringSubscription",
            "cloudfront:DeleteOriginRequestPolicy",
            "cloudfront:DeletePublicKey",
            "cloudfront:DeleteResponseHeadersPolicy",
            "cloudfront:GetCachePolicy",
            "cloudfront:GetCachePolicyConfig",
            "cloudfront:GetDistribution",
            "cloudfront:GetDistributionConfig",
            "cloudfront:GetFieldLevelEncryption",
            "cloudfront:GetFieldLevelEncryptionConfig",
            "cloudfront:GetFieldLevelEncryptionProfile",
            "cloudfront:GetFieldLevelEncryptionProfileConfig",
            "cloudfront:GetInvalidation",
            "cloudfront:GetKeyGroup",
            "cloudfront:GetKeyGroupConfig",
            "cloudfront:GetMonitoringSubscription",
            "cloudfront:GetOriginRequestPolicy",
            "cloudfront:GetOriginRequestPolicyConfig",
            "cloudfront:GetPublicKey",
            "cloudfront:GetPublicKeyConfig",
            "cloudfront:GetResponseHeadersPolicy",
            "cloudfront:GetResponseHeadersPolicyConfig",
            "cloudfront:ListCachePolicies",
            "cloudfront:ListConflictingAliases",
            "cloudfront:ListDistributions",
            "cloudfront:ListInvalidations",
            "cloudfront:ListTagsForResource",
            "cloudfront:TagResource",
            "cloudfront:UntagResource",
            "cloudfront:UpdateCachePolicy",
            "cloudfront:UpdateDistribution",
            "cloudfront:UpdateFieldLevelEncryptionConfig",
            "cloudfront:UpdateFieldLevelEncryptionProfile",
            "cloudfront:UpdateKeyGroup",
            "cloudfront:UpdateOriginRequestPolicy",
            "cloudfront:UpdatePublicKey",
            "cloudfront:UpdateResponseHeadersPolicy"
          ],
          Effect   = "Allow",
          Resource = "*"
        },
        {
          Sid = "Stmt1664391600725",
          Action = [
            "route53:ActivateKeySigningKey",
            "route53:AssociateVPCWithHostedZone",
            "route53:ChangeResourceRecordSets",
            "route53:ChangeTagsForResource",
            "route53:CreateHostedZone",
            "route53:CreateKeySigningKey",
            "route53:DeactivateKeySigningKey",
            "route53:DeleteHostedZone",
            "route53:DeleteKeySigningKey",
            "route53:DisableHostedZoneDNSSEC",
            "route53:EnableHostedZoneDNSSEC",
            "route53:GetChange",
            "route53:GetDNSSEC",
            "route53:GetHostedZone",
            "route53:GetHostedZoneCount",
            "route53:GetHostedZoneLimit",
            "route53:ListHostedZones",
            "route53:ListHostedZonesByName",
            "route53:ListHostedZonesByVPC",
            "route53:ListResourceRecordSets",
            "route53:ListTagsForResource",
            "route53:ListTagsForResources",
            "route53:UpdateHostedZoneComment"
          ],
          Effect   = "Allow",
          Resource = "*"
        },
      ]
    }

    security = {
      Version = "2012-10-17",
      Statement = [
        {
          Sid = "Stmt1664386851987",
          Action = [
            "acm:AddTagsToCertificate",
            "acm:DeleteCertificate",
            "acm:DescribeCertificate",
            "acm:ExportCertificate",
            "acm:GetAccountConfiguration",
            "acm:GetCertificate",
            "acm:ListCertificates",
            "acm:ListTagsForCertificate",
            "acm:PutAccountConfiguration",
            "acm:RemoveTagsFromCertificate",
            "acm:RenewCertificate",
            "acm:RequestCertificate",
            "acm:ResendValidationEmail",
            "acm:UpdateCertificateOptions"
          ],
          Effect   = "Allow",
          Resource = "*"
        },
        {
          Sid = "Stmt1664391375625",
          Action = [
            "iam:AddRoleToInstanceProfile",
            "iam:AddUserToGroup",
            "iam:AttachGroupPolicy",
            "iam:AttachRolePolicy",
            "iam:AttachUserPolicy",
            "iam:ChangePassword",
            "iam:CreateAccessKey",
            "iam:CreateGroup",
            "iam:CreateInstanceProfile",
            "iam:CreateLoginProfile",
            "iam:CreatePolicy",
            "iam:CreatePolicyVersion",
            "iam:CreateRole",
            "iam:CreateServiceLinkedRole",
            "iam:CreateServiceSpecificCredential",
            "iam:CreateUser",
            "iam:CreateVirtualMFADevice",
            "iam:DeactivateMFADevice",
            "iam:DeleteAccessKey",
            "iam:DeleteAccountPasswordPolicy",
            "iam:DeleteGroup",
            "iam:DeleteGroupPolicy",
            "iam:DeleteInstanceProfile",
            "iam:DeleteLoginProfile",
            "iam:DeletePolicy",
            "iam:DeletePolicyVersion",
            "iam:DeleteRole",
            "iam:DeleteRolePolicy",
            "iam:DeleteUser",
            "iam:DeleteUserPolicy",
            "iam:DeleteVirtualMFADevice",
            "iam:DetachGroupPolicy",
            "iam:DetachRolePolicy",
            "iam:DetachUserPolicy",
            "iam:EnableMFADevice",
            "iam:GetAccessKeyLastUsed",
            "iam:GetAccountAuthorizationDetails",
            "iam:GetAccountPasswordPolicy",
            "iam:GetAccountSummary",
            "iam:GetContextKeysForCustomPolicy",
            "iam:GetContextKeysForPrincipalPolicy",
            "iam:GetGroup",
            "iam:GetGroupPolicy",
            "iam:GetInstanceProfile",
            "iam:GetLoginProfile",
            "iam:GetPolicy",
            "iam:GetPolicyVersion",
            "iam:GetRole",
            "iam:GetRolePolicy",
            "iam:GetUser",
            "iam:GetUserPolicy",
            "iam:ListAccessKeys",
            "iam:ListAccountAliases",
            "iam:ListAttachedGroupPolicies",
            "iam:ListAttachedRolePolicies",
            "iam:ListAttachedUserPolicies",
            "iam:ListEntitiesForPolicy",
            "iam:ListGroupPolicies",
            "iam:ListGroups",
            "iam:ListGroupsForUser",
            "iam:ListInstanceProfileTags",
            "iam:ListInstanceProfiles",
            "iam:ListInstanceProfilesForRole",
            "iam:ListMFADeviceTags",
            "iam:ListMFADevices",
            "iam:ListPolicies",
            "iam:ListPolicyTags",
            "iam:ListPolicyVersions",
            "iam:ListRolePolicies",
            "iam:ListRoleTags",
            "iam:ListRoles",
            "iam:ListUserPolicies",
            "iam:ListUserTags",
            "iam:ListUsers",
            "iam:ListVirtualMFADevices",
            "iam:PassRole",
            "iam:PutGroupPolicy",
            "iam:PutRolePermissionsBoundary",
            "iam:PutRolePolicy",
            "iam:PutUserPermissionsBoundary",
            "iam:PutUserPolicy",
            "iam:RemoveRoleFromInstanceProfile",
            "iam:RemoveUserFromGroup",
            "iam:ResyncMFADevice",
            "iam:SetDefaultPolicyVersion",
            "iam:TagInstanceProfile",
            "iam:TagMFADevice",
            "iam:TagPolicy",
            "iam:TagRole",
            "iam:TagUser",
            "iam:UntagInstanceProfile",
            "iam:UntagMFADevice",
            "iam:UntagPolicy",
            "iam:UntagRole",
            "iam:UntagUser",
            "iam:UpdateAccessKey",
            "iam:UpdateAccountPasswordPolicy",
            "iam:UpdateAssumeRolePolicy",
            "iam:UpdateGroup",
            "iam:UpdateLoginProfile",
            "iam:UpdateRole",
            "iam:UpdateRoleDescription",
            "iam:UpdateUser"
          ],
          Effect   = "Allow",
          Resource = "*"
        },
        {
          Sid = "Stmt1664392616955",
          Action = [
            "ssm:AddTagsToResource",
            "ssm:DeleteParameter",
            "ssm:DeleteParameters",
            "ssm:DescribeParameters",
            "ssm:GetParameter",
            "ssm:GetParameterHistory",
            "ssm:GetParameters",
            "ssm:GetParametersByPath",
            "ssm:ListTagsForResource",
            "ssm:LabelParameterVersion",
            "ssm:PutParameter",
            "ssm:RemoveTagsFromResource",
            "ssm:UnlabelParameterVersion"
          ],
          Effect   = "Allow",
          Resource = "*"
        },
      ]
    }

    storage = {
      Version = "2012-10-17",
      Statement = [
        {
          Sid = "Stmt1664391913340",
          Action = [
            "s3:AbortMultipartUpload",
            "s3:CreateAccessPoint",
            "s3:CreateBucket",
            "s3:DeleteAccessPoint",
            "s3:DeleteAccessPointPolicy",
            "s3:DeleteBucket",
            "s3:DeleteBucketPolicy",
            "s3:DeleteBucketWebsite",
            "s3:DeleteObject",
            "s3:DeleteObjectTagging",
            "s3:DeleteObjectVersion",
            "s3:DeleteObjectVersionTagging",
            "s3:GetAccelerateConfiguration",
            "s3:GetAccessPoint",
            "s3:GetAccessPointPolicy",
            "s3:GetAccessPointPolicyStatus",
            "s3:GetAccountPublicAccessBlock",
            "s3:GetBucketAcl",
            "s3:GetBucketCORS",
            "s3:GetBucketLocation",
            "s3:GetBucketLogging",
            "s3:GetBucketNotification",
            "s3:GetBucketObjectLockConfiguration",
            "s3:GetBucketOwnershipControls",
            "s3:GetBucketPolicy",
            "s3:GetBucketPolicyStatus",
            "s3:GetBucketPublicAccessBlock",
            "s3:GetBucketRequestPayment",
            "s3:GetBucketTagging",
            "s3:GetBucketVersioning",
            "s3:GetBucketWebsite",
            "s3:GetEncryptionConfiguration",
            "s3:GetIntelligentTieringConfiguration",
            "s3:GetLifecycleConfiguration",
            "s3:GetObject",
            "s3:GetObjectAcl",
            "s3:GetObjectAttributes",
            "s3:GetObjectLegalHold",
            "s3:GetObjectRetention",
            "s3:GetObjectTagging",
            "s3:GetObjectVersion",
            "s3:GetObjectVersionAcl",
            "s3:GetObjectVersionAttributes",
            "s3:GetObjectVersionForReplication",
            "s3:GetObjectVersionTagging",
            "s3:GetReplicationConfiguration",
            "s3:ListAccessPoints",
            "s3:ListAllMyBuckets",
            "s3:ListBucket",
            "s3:ListBucketVersions",
            "s3:ListMultiRegionAccessPoints",
            "s3:PutAccessPointPolicy",
            "s3:PutBucketAcl",
            "s3:PutBucketCORS",
            "s3:PutBucketLogging",
            "s3:PutBucketNotification",
            "s3:PutBucketObjectLockConfiguration",
            "s3:PutBucketOwnershipControls",
            "s3:PutBucketPolicy",
            "s3:PutBucketRequestPayment",
            "s3:PutBucketTagging",
            "s3:PutBucketVersioning",
            "s3:PutBucketWebsite",
            "s3:PutEncryptionConfiguration",
            "s3:PutIntelligentTieringConfiguration",
            "s3:PutInventoryConfiguration",
            "s3:PutLifecycleConfiguration",
            "s3:PutMultiRegionAccessPointPolicy",
            "s3:PutObject",
            "s3:PutObjectAcl",
            "s3:PutObjectLegalHold",
            "s3:PutObjectRetention",
            "s3:PutObjectTagging",
            "s3:PutObjectVersionAcl",
            "s3:PutObjectVersionTagging",
            "s3:ReplicateDelete",
            "s3:ReplicateObject",
            "s3:ReplicateTags",
            "s3:RestoreObject"
          ],
          Effect   = "Allow",
          Resource = "*"
        },
      ]
    }
  }
}
